// Artikel panduan untuk pengunjung dari mesin pencari.
// Blok isi: { h: 'Subjudul' } | { p: 'Paragraf' } | { ul: ['butir', ...] } | { cta: true }
// Contoh soal di artikel adalah ilustrasi buatan sendiri, bukan butir asli
// instrumen berhak cipta. Rute & SEO dibuat otomatis dari daftar ini
// (lihat config/seo.js); setelah menambah artikel, buat ulang public/sitemap.xml.

export const ARTIKEL = [
  {
    slug: 'tes-papi-kostick',
    judul: 'Tes PAPI Kostick: Cara Kerja, 20 Aspek yang Diukur, dan Tips Mengerjakannya',
    judulSeo: 'Tes PAPI Kostick: Cara Kerja, 20 Aspek & Tips Mengerjakan',
    deskripsi: 'Panduan lengkap tes PAPI Kostick untuk psikotes kerja: bentuk soal, 20 aspek kepribadian kerja yang diukur, cara HR membaca hasilnya, dan tips mengerjakan dengan tenang.',
    ringkas: 'Bentuk soal, 20 aspek yang diukur, cara HR membaca hasilnya, dan tips agar jawaban Anda tetap konsisten.',
    tanggal: '2026-10-06',
    menit: 6,
    tes: { route: '/tes-papi', label: 'Coba latihan tes PAPI Kostick' },
    isi: [
      { p: 'Kalau Anda pernah mengikuti psikotes rekrutmen perusahaan atau BUMN, besar kemungkinan Anda pernah bertemu soal berisi dua pernyataan yang harus dipilih salah satunya, berulang-ulang hingga puluhan nomor. Itulah tes PAPI Kostick, salah satu tes kepribadian kerja yang paling sering dipakai di Indonesia.' },
      { h: 'Apa itu tes PAPI Kostick?' },
      { p: 'PAPI (Perception and Preference Inventory) dikembangkan oleh Dr. Max Kostick untuk menggambarkan perilaku dan preferensi seseorang di lingkungan kerja. Tes ini tidak mengukur kecerdasan dan tidak ada jawaban benar atau salah. Yang dilihat adalah pola: hal apa yang Anda butuhkan agar nyaman bekerja, dan peran apa yang cenderung Anda ambil.' },
      { h: 'Bentuk soalnya seperti apa?' },
      { p: 'Versi yang umum dipakai berisi 90 pasangan pernyataan. Di setiap nomor Anda wajib memilih satu pernyataan yang paling menggambarkan diri Anda, meskipun keduanya terasa cocok atau sama-sama kurang cocok. Format seperti ini disebut forced choice. Sebagai ilustrasi (bukan soal asli), satu nomor bisa terlihat seperti ini:' },
      { ul: ['A. Saya senang menyelesaikan pekerjaan sampai tuntas sebelum memulai yang baru.', 'B. Saya senang bekerja bersama orang lain dalam kelompok.'] },
      { p: 'Karena harus memilih, setiap jawaban menambah skor pada salah satu aspek. Dari 90 pilihan itulah terbentuk profil 20 aspek.' },
      { h: '20 aspek yang diukur' },
      { p: 'Aspek PAPI biasanya dikelompokkan ke dalam beberapa area. Pembagian di bawah ini sama dengan yang dipakai pada laporan AssesIN:' },
      { ul: [
        'Kepemimpinan: peran memimpin (L), kebutuhan mengendalikan orang lain (P), dan kemudahan mengambil keputusan (I).',
        'Arah kerja: kebutuhan berprestasi (N), kebutuhan akan status (A), dan ketergantungan pada kelompok (G).',
        'Aktivitas: tempo kerja (T), semangat dan energi (V), serta kebutuhan beraktivitas (X).',
        'Hubungan sosial: kebutuhan kasih sayang (Z), rasa memiliki kelompok (B), kebutuhan menjalin hubungan (O), dan keluasan pergaulan (S).',
        'Temperamen: ketegasan (K) dan kestabilan emosi (E).',
        'Sikap terhadap atasan dan aturan: mendukung otoritas (F) dan kebutuhan akan aturan (W).',
        'Gaya kerja: kebutuhan akan perubahan (C), kebutuhan diperhatikan (D), dan peran pekerja keras (R).',
      ] },
      { h: 'Bagaimana HR membaca hasilnya?' },
      { p: 'Hasil PAPI hampir selalu dibaca dengan mencocokkan profil Anda dengan kebutuhan posisi. Skor tinggi tidak otomatis bagus. Kebutuhan aturan (W) yang tinggi cocok untuk posisi yang menuntut kepatuhan prosedur, tetapi bisa menjadi tantangan di posisi yang serba cepat berubah. Peran memimpin (L) yang tinggi dicari untuk calon supervisor, tetapi tidak wajib untuk staf ahli yang bekerja mandiri.' },
      { p: 'Pewawancara juga sering memakai hasil PAPI sebagai bahan pertanyaan. Jika skor kebutuhan perubahan (C) Anda tinggi, jangan kaget bila ditanya bagaimana Anda menghadapi pekerjaan rutin.' },
      { h: 'Tips mengerjakan tes PAPI Kostick' },
      { ul: [
        'Jawab jujur sesuai kebiasaan Anda di tempat kerja, bukan sesuai sosok ideal yang Anda bayangkan. Profil yang dibuat-buat mudah terlihat tidak konsisten.',
        'Jangan terlalu lama berpikir. Pilihan pertama biasanya paling mencerminkan diri Anda, dan banyak pasangan pernyataan memang sengaja dibuat sama-sama positif.',
        'Bayangkan konteks kerja, bukan kehidupan pribadi, karena tes ini menilai perilaku kerja.',
        'Isi semua nomor. Jawaban yang kosong membuat profil tidak bisa dibaca dengan baik.',
        'Kenali pola Anda sebelum hari tes. Latihan membantu Anda tidak kaget dengan formatnya dan lebih siap menjelaskan hasilnya saat wawancara.',
      ] },
      { h: 'Berlatih sebelum tes yang sebenarnya' },
      { p: 'Latihan tidak dimaksudkan untuk "mengakali" hasil. Tujuannya agar Anda terbiasa dengan format 90 pasangan, tahu kira-kira berapa lama waktu yang dibutuhkan, dan memahami gambaran profil Anda sendiri. Di AssesIN Anda bisa mengerjakan latihan PAPI Kostick secara gratis dan langsung melihat ringkasan hasilnya.' },
      { cta: true },
    ],
  },
  {
    slug: 'apa-itu-tes-disc',
    judul: 'Apa Itu Tes DISC? Arti Tipe D, I, S, dan C dalam Rekrutmen',
    judulSeo: 'Apa Itu Tes DISC? Arti Tipe D, I, S, C dalam Rekrutmen',
    deskripsi: 'Penjelasan tes DISC: asal-usul, arti tipe Dominance, Influence, Steadiness, dan Compliance, contoh perilaku kerja tiap tipe, serta cara perusahaan memakai DISC saat rekrutmen.',
    ringkas: 'Asal-usul DISC, arti keempat tipe, contoh perilakunya di kantor, dan cara perusahaan memakainya saat seleksi.',
    tanggal: '2026-10-06',
    menit: 5,
    tes: { route: '/tes-disc', label: 'Coba tes DISC gratis' },
    isi: [
      { p: 'DISC adalah salah satu alat yang paling sering dipakai HR untuk membaca gaya perilaku kerja seseorang. Tesnya relatif singkat, hasilnya mudah dipahami, dan bisa langsung dikaitkan dengan cara seseorang berkomunikasi, mengambil keputusan, dan bekerja dalam tim.' },
      { h: 'Asal-usul DISC' },
      { p: 'Model DISC berakar dari tulisan psikolog William Moulton Marston pada akhir 1920-an tentang emosi dan perilaku orang normal. Model ini kemudian dikembangkan menjadi berbagai instrumen asesmen yang dipakai di dunia kerja hingga sekarang. DISC menggambarkan gaya perilaku, bukan kecerdasan dan bukan gangguan kepribadian.' },
      { h: 'Arti empat tipe DISC' },
      { ul: [
        'D (Dominance): berorientasi pada hasil, tegas, suka tantangan, dan cepat mengambil keputusan. Di kantor biasanya terlihat sebagai orang yang mendorong target dan tidak sabar dengan proses yang bertele-tele.',
        'I (Influence): antusias, persuasif, dan senang berinteraksi. Biasanya pandai membangun suasana, mempresentasikan ide, dan menggerakkan orang lain.',
        'S (Steadiness): sabar, stabil, dan suportif. Menyukai ritme kerja yang konsisten, menjadi pendengar yang baik, dan setia pada tim.',
        'C (Compliance atau Conscientiousness): teliti, analitis, dan mengutamakan akurasi serta standar. Senang bekerja dengan data dan prosedur yang jelas.',
      ] },
      { p: 'Hampir tidak ada orang yang murni satu tipe. Hasil DISC biasanya berupa kombinasi, misalnya profil DI (tegas sekaligus persuasif) atau SC (stabil sekaligus teliti). Kombinasi inilah yang memberi gambaran lebih utuh.' },
      { h: 'Bentuk soal tes DISC' },
      { p: 'Pada format yang umum, setiap nomor berisi beberapa kata sifat. Anda diminta memilih satu kata yang paling menggambarkan diri Anda dan satu kata yang paling tidak menggambarkan diri Anda. Contoh ilustrasi (bukan soal asli): dari kata "tegas", "ramah", "sabar", dan "teliti", Anda memilih yang paling dan paling tidak mirip dengan diri Anda.' },
      { p: 'Dari pilihan "paling" dan "paling tidak" itu terbentuk beberapa grafik yang menggambarkan perilaku yang Anda tampilkan di depan orang lain, perilaku saat di bawah tekanan, dan gambaran diri Anda secara umum.' },
      { h: 'Bagaimana perusahaan memakai DISC?' },
      { ul: [
        'Mencocokkan gaya kerja dengan tuntutan posisi. Posisi sales sering cocok dengan profil I atau D, sedangkan posisi quality control atau keuangan sering cocok dengan profil C.',
        'Menyusun tim yang seimbang, agar tidak semua anggota punya gaya yang sama.',
        'Bahan wawancara: pewawancara dapat menanyakan pengalaman yang sesuai atau bertolak belakang dengan profil Anda.',
      ] },
      { p: 'Tidak ada tipe DISC yang lebih baik dari tipe lain. Yang dinilai adalah kecocokan dengan pekerjaan dan lingkungan.' },
      { h: 'Tips mengerjakan tes DISC' },
      { ul: [
        'Bayangkan diri Anda dalam situasi kerja sehari-hari, lalu pilih dengan jujur.',
        'Jangan berusaha terlihat sebagai tipe tertentu. Jawaban yang tidak konsisten membuat grafik sulit dibaca dan justru menimbulkan pertanyaan.',
        'Kerjakan dengan cukup cepat. Tes DISC umumnya hanya butuh beberapa menit.',
        'Pahami profil Anda sendiri agar bisa menjelaskan kekuatan dan area pengembangan saat wawancara.',
      ] },
      { cta: true },
    ],
  },
  {
    slug: 'persiapan-psikotes-kerja',
    judul: 'Persiapan Psikotes Kerja: Jenis Tes yang Sering Muncul dan Cara Menghadapinya',
    judulSeo: 'Persiapan Psikotes Kerja: Jenis Tes yang Sering Muncul (CPNS, BUMN, Swasta)',
    deskripsi: 'Panduan persiapan psikotes untuk rekrutmen kerja, BUMN, dan CPNS: jenis tes kepribadian, kemampuan, ketelitian, dan tes menggambar yang sering muncul, plus tips sebelum dan saat tes.',
    ringkas: 'Jenis tes yang umum di rekrutmen swasta, BUMN, dan CPNS, beserta persiapan yang benar-benar membantu.',
    tanggal: '2026-10-06',
    menit: 7,
    tes: { route: '/', label: 'Lihat semua latihan tes', hash: 'tes' },
    isi: [
      { p: 'Psikotes adalah salah satu tahap seleksi yang paling membuat cemas, terutama karena banyak orang tidak tahu tes apa yang akan muncul. Kabar baiknya, jenis tes yang dipakai dalam rekrutmen relatif bisa ditebak. Dengan mengenal formatnya lebih dulu, Anda bisa datang lebih tenang.' },
      { p: 'Catatan: susunan tes berbeda di setiap perusahaan, instansi, dan tahun seleksi. Selalu cek pengumuman resmi rekrutmen yang Anda ikuti.' },
      { h: '1. Tes kepribadian' },
      { p: 'Tes kepribadian menggambarkan gaya kerja, kebutuhan, dan cara Anda berinteraksi. Tidak ada jawaban benar atau salah. Yang dinilai adalah kecocokan dengan posisi dan konsistensi jawaban. Beberapa yang sering dipakai:' },
      { ul: [
        'PAPI Kostick: 90 pasangan pernyataan tentang perilaku kerja, menghasilkan profil 20 aspek.',
        'DISC: memilih kata sifat yang paling dan paling tidak menggambarkan diri, untuk membaca gaya perilaku kerja.',
        'Tes kepribadian lain seperti EPPS atau inventori berbasis model Big Five, tergantung kebijakan penyelenggara.',
      ] },
      { p: 'Persiapan terbaik untuk tes kepribadian adalah memahami diri sendiri, bukan menghafal jawaban "ideal".' },
      { h: '2. Tes kemampuan kognitif' },
      { p: 'Bagian ini menguji kemampuan berpikir dan biasanya punya jawaban benar. Umumnya terdiri dari kemampuan verbal (sinonim, antonim, analogi), numerik (deret angka, hitungan cepat, soal cerita), logika (silogisme, penalaran), dan spasial atau figural (pola gambar). Untuk bagian ini, latihan soal benar-benar membantu karena kecepatan sangat berpengaruh.' },
      { h: '3. Tes ketelitian dan ketahanan kerja' },
      { p: 'Tes seperti Kraepelin atau Pauli meminta Anda menjumlahkan angka-angka secara berurutan dalam waktu terbatas, kolom demi kolom. Yang dilihat bukan hanya jumlah jawaban benar, tetapi juga kestabilan tempo, ketelitian, dan daya tahan dari awal hingga akhir. Kuncinya: jaga ritme stabil, jangan ngebut di awal lalu kelelahan di akhir.' },
      { h: '4. Tes menggambar (proyektif)' },
      { p: 'Beberapa seleksi memakai tes menggambar, misalnya menggambar orang, pohon, atau melanjutkan pola pada kotak-kotak. Gambar dinilai oleh psikolog dari berbagai sisi, bukan dari bagus tidaknya. Gambarlah dengan wajar dan lengkap, tidak perlu artistik, dan selesaikan dalam waktu yang diberikan.' },
      { h: 'Bagaimana dengan CPNS dan BUMN?' },
      { p: 'Pada seleksi CPNS, tahap Seleksi Kompetensi Dasar (SKD) berbasis komputer berisi Tes Wawasan Kebangsaan, Tes Intelegensia Umum, dan Tes Karakteristik Pribadi. Sebagian instansi menambahkan psikotes atau tes kepribadian pada tahap seleksi berikutnya, sesuai kebutuhan jabatan.' },
      { p: 'Rekrutmen BUMN umumnya memiliki tahap tes kemampuan dasar, tes yang berkaitan dengan nilai-nilai perusahaan, dan tes kepribadian, lalu dilanjutkan wawancara. Rinciannya dapat berubah dari tahun ke tahun, jadi pantau situs resmi penyelenggara.' },
      { h: 'Tips sebelum hari tes' },
      { ul: [
        'Tidur cukup. Tes ketelitian dan kemampuan sangat dipengaruhi kondisi fisik.',
        'Kenali format tes kepribadian lebih dulu agar tidak kaget dengan soal yang berulang dan bentuk pilihan paksa.',
        'Latih soal hitungan dan logika dengan batas waktu.',
        'Siapkan perlengkapan sesuai instruksi (alat tulis, kartu identitas) dan datang lebih awal.',
      ] },
      { h: 'Tips saat mengerjakan' },
      { ul: [
        'Baca instruksi sampai selesai. Banyak kesalahan terjadi karena salah memahami cara menjawab.',
        'Pada tes kemampuan, lewati soal yang terlalu sulit dan kembali jika masih ada waktu.',
        'Pada tes kepribadian, jawab jujur dan konsisten. Jangan menebak "jawaban yang diinginkan perusahaan".',
        'Tetap tenang jika tidak semua soal selesai. Banyak tes memang dirancang agar sulit diselesaikan seluruhnya.',
      ] },
      { p: 'Latihan tes kepribadian seperti PAPI Kostick, DISC, MSDT, Big Five, dan Resiliensi Kerja bisa Anda kerjakan gratis di AssesIN untuk mengenal pola diri sebelum menghadapi seleksi.' },
      { cta: true },
    ],
  },
]

export const ARTIKEL_BY_SLUG = Object.fromEntries(ARTIKEL.map(a => [a.slug, a]))
