// Artikel panduan untuk pengunjung dari mesin pencari.
// Blok isi: { h: 'Subjudul' } | { p: 'Paragraf' } | { ul: ['butir', ...] } | { cta: true }
// Contoh soal di artikel adalah ilustrasi buatan sendiri, bukan butir asli
// instrumen berhak cipta. Rute & SEO dibuat otomatis dari daftar ini
// (lihat config/seo.js); setelah menambah artikel, buat ulang public/sitemap.xml.

export const ARTIKEL = [
  {
    slug: 'tes-papi-kostick',
    judul: 'Tes PAPI Kostick: Cara Kerja, 20 Aspek yang Diukur, dan Tips Mengerjakannya',
    judulSeo: 'Tes PAPI Kostick: Cara Kerja, 20 Aspek & Tips Mengerjakan',
    deskripsi: 'Panduan lengkap tes PAPI Kostick untuk psikotes kerja: bentuk soal, 20 aspek kepribadian kerja yang diukur, cara HR membaca hasilnya, dan tips mengerjakan dengan tenang.',
    ringkas: 'Bentuk soal, 20 aspek yang diukur, cara HR membaca hasilnya, dan tips agar jawaban Anda tetap konsisten.',
    tanggal: '2026-10-06',
    menit: 6,
    tes: { route: '/tes-papi', label: 'Coba latihan tes PAPI Kostick' },
    isi: [
      { p: 'Kalau Anda pernah mengikuti psikotes rekrutmen perusahaan atau BUMN, besar kemungkinan Anda pernah bertemu soal berisi dua pernyataan yang harus dipilih salah satunya, berulang-ulang hingga puluhan nomor. Itulah tes PAPI Kostick, salah satu tes kepribadian kerja yang paling sering dipakai di Indonesia.' },
      { h: 'Apa itu tes PAPI Kostick?' },
      { p: 'PAPI (Perception and Preference Inventory) dikembangkan oleh Dr. Max Kostick untuk menggambarkan perilaku dan preferensi seseorang di lingkungan kerja. Tes ini tidak mengukur kecerdasan dan tidak ada jawaban benar atau salah. Yang dilihat adalah pola: hal apa yang Anda butuhkan agar nyaman bekerja, dan peran apa yang cenderung Anda ambil.' },
      { h: 'Bentuk soalnya seperti apa?' },
      { p: 'Versi yang umum dipakai berisi 90 pasangan pernyataan. Di setiap nomor Anda wajib memilih satu pernyataan yang paling menggambarkan diri Anda, meskipun keduanya terasa cocok atau sama-sama kurang cocok. Format seperti ini disebut forced choice. Sebagai ilustrasi (bukan soal asli), satu nomor bisa terlihat seperti ini:' },
      { ul: ['A. Saya senang menyelesaikan pekerjaan sampai tuntas sebelum memulai yang baru.', 'B. Saya senang bekerja bersama orang lain dalam kelompok.'] },
      { p: 'Karena harus memilih, setiap jawaban menambah skor pada salah satu aspek. Dari 90 pilihan itulah terbentuk profil 20 aspek.' },
      { h: '20 aspek yang diukur' },
      { p: 'Aspek PAPI biasanya dikelompokkan ke dalam beberapa area. Pembagian di bawah ini sama dengan yang dipakai pada laporan AssesIN:' },
      { ul: [
        'Kepemimpinan: peran memimpin (L), kebutuhan mengendalikan orang lain (P), dan kemudahan mengambil keputusan (I).',
        'Arah kerja: kebutuhan berprestasi (N), kebutuhan akan status (A), dan ketergantungan pada kelompok (G).',
        'Aktivitas: tempo kerja (T), semangat dan energi (V), serta kebutuhan beraktivitas (X).',
        'Hubungan sosial: kebutuhan kasih sayang (Z), rasa memiliki kelompok (B), kebutuhan menjalin hubungan (O), dan keluasan pergaulan (S).',
        'Temperamen: ketegasan (K) dan kestabilan emosi (E).',
        'Sikap terhadap atasan dan aturan: mendukung otoritas (F) dan kebutuhan akan aturan (W).',
        'Gaya kerja: kebutuhan akan perubahan (C), kebutuhan diperhatikan (D), dan peran pekerja keras (R).',
      ] },
      { h: 'Bagaimana HR membaca hasilnya?' },
      { p: 'Hasil PAPI hampir selalu dibaca dengan mencocokkan profil Anda dengan kebutuhan posisi. Skor tinggi tidak otomatis bagus. Kebutuhan aturan (W) yang tinggi cocok untuk posisi yang menuntut kepatuhan prosedur, tetapi bisa menjadi tantangan di posisi yang serba cepat berubah. Peran memimpin (L) yang tinggi dicari untuk calon supervisor, tetapi tidak wajib untuk staf ahli yang bekerja mandiri.' },
      { p: 'Pewawancara juga sering memakai hasil PAPI sebagai bahan pertanyaan. Jika skor kebutuhan perubahan (C) Anda tinggi, jangan kaget bila ditanya bagaimana Anda menghadapi pekerjaan rutin.' },
      { h: 'Tips mengerjakan tes PAPI Kostick' },
      { ul: [
        'Jawab jujur sesuai kebiasaan Anda di tempat kerja, bukan sesuai sosok ideal yang Anda bayangkan. Profil yang dibuat-buat mudah terlihat tidak konsisten.',
        'Jangan terlalu lama berpikir. Pilihan pertama biasanya paling mencerminkan diri Anda, dan banyak pasangan pernyataan memang sengaja dibuat sama-sama positif.',
        'Bayangkan konteks kerja, bukan kehidupan pribadi, karena tes ini menilai perilaku kerja.',
        'Isi semua nomor. Jawaban yang kosong membuat profil tidak bisa dibaca dengan baik.',
        'Kenali pola Anda sebelum hari tes. Latihan membantu Anda tidak kaget dengan formatnya dan lebih siap menjelaskan hasilnya saat wawancara.',
      ] },
      { h: 'Berlatih sebelum tes yang sebenarnya' },
      { p: 'Latihan tidak dimaksudkan untuk "mengakali" hasil. Tujuannya agar Anda terbiasa dengan format 90 pasangan, tahu kira-kira berapa lama waktu yang dibutuhkan, dan memahami gambaran profil Anda sendiri. Di AssesIN Anda bisa mengerjakan latihan PAPI Kostick secara gratis dan langsung melihat ringkasan hasilnya.' },
      { cta: true },
    ],
  },
  {
    slug: 'apa-itu-tes-disc',
    judul: 'Apa Itu Tes DISC? Arti Tipe D, I, S, dan C dalam Rekrutmen',
    judulSeo: 'Apa Itu Tes DISC? Arti Tipe D, I, S, C dalam Rekrutmen',
    deskripsi: 'Penjelasan tes DISC: asal-usul, arti tipe Dominance, Influence, Steadiness, dan Compliance, contoh perilaku kerja tiap tipe, serta cara perusahaan memakai DISC saat rekrutmen.',
    ringkas: 'Asal-usul DISC, arti keempat tipe, contoh perilakunya di kantor, dan cara perusahaan memakainya saat seleksi.',
    tanggal: '2026-10-06',
    menit: 5,
    tes: { route: '/tes-disc', label: 'Coba tes DISC gratis' },
    isi: [
      { p: 'DISC adalah salah satu alat yang paling sering dipakai HR untuk membaca gaya perilaku kerja seseorang. Tesnya relatif singkat, hasilnya mudah dipahami, dan bisa langsung dikaitkan dengan cara seseorang berkomunikasi, mengambil keputusan, dan bekerja dalam tim.' },
      { h: 'Asal-usul DISC' },
      { p: 'Model DISC berakar dari tulisan psikolog William Moulton Marston pada akhir 1920-an tentang emosi dan perilaku orang normal. Model ini kemudian dikembangkan menjadi berbagai instrumen asesmen yang dipakai di dunia kerja hingga sekarang. DISC menggambarkan gaya perilaku, bukan kecerdasan dan bukan gangguan kepribadian.' },
      { h: 'Arti empat tipe DISC' },
      { ul: [
        'D (Dominance): berorientasi pada hasil, tegas, suka tantangan, dan cepat mengambil keputusan. Di kantor biasanya terlihat sebagai orang yang mendorong target dan tidak sabar dengan proses yang bertele-tele.',
        'I (Influence): antusias, persuasif, dan senang berinteraksi. Biasanya pandai membangun suasana, mempresentasikan ide, dan menggerakkan orang lain.',
        'S (Steadiness): sabar, stabil, dan suportif. Menyukai ritme kerja yang konsisten, menjadi pendengar yang baik, dan setia pada tim.',
        'C (Compliance atau Conscientiousness): teliti, analitis, dan mengutamakan akurasi serta standar. Senang bekerja dengan data dan prosedur yang jelas.',
      ] },
      { p: 'Hampir tidak ada orang yang murni satu tipe. Hasil DISC biasanya berupa kombinasi, misalnya profil DI (tegas sekaligus persuasif) atau SC (stabil sekaligus teliti). Kombinasi inilah yang memberi gambaran lebih utuh.' },
      { h: 'Bentuk soal tes DISC' },
      { p: 'Pada format yang umum, setiap nomor berisi beberapa kata sifat. Anda diminta memilih satu kata yang paling menggambarkan diri Anda dan satu kata yang paling tidak menggambarkan diri Anda. Contoh ilustrasi (bukan soal asli): dari kata "tegas", "ramah", "sabar", dan "teliti", Anda memilih yang paling dan paling tidak mirip dengan diri Anda.' },
      { p: 'Dari pilihan "paling" dan "paling tidak" itu terbentuk beberapa grafik yang menggambarkan perilaku yang Anda tampilkan di depan orang lain, perilaku saat di bawah tekanan, dan gambaran diri Anda secara umum.' },
      { h: 'Bagaimana perusahaan memakai DISC?' },
      { ul: [
        'Mencocokkan gaya kerja dengan tuntutan posisi. Posisi sales sering cocok dengan profil I atau D, sedangkan posisi quality control atau keuangan sering cocok dengan profil C.',
        'Menyusun tim yang seimbang, agar tidak semua anggota punya gaya yang sama.',
        'Bahan wawancara: pewawancara dapat menanyakan pengalaman yang sesuai atau bertolak belakang dengan profil Anda.',
      ] },
      { p: 'Tidak ada tipe DISC yang lebih baik dari tipe lain. Yang dinilai adalah kecocokan dengan pekerjaan dan lingkungan.' },
      { h: 'Tips mengerjakan tes DISC' },
      { ul: [
        'Bayangkan diri Anda dalam situasi kerja sehari-hari, lalu pilih dengan jujur.',
        'Jangan berusaha terlihat sebagai tipe tertentu. Jawaban yang tidak konsisten membuat grafik sulit dibaca dan justru menimbulkan pertanyaan.',
        'Kerjakan dengan cukup cepat. Tes DISC umumnya hanya butuh beberapa menit.',
        'Pahami profil Anda sendiri agar bisa menjelaskan kekuatan dan area pengembangan saat wawancara.',
      ] },
      { cta: true },
    ],
  },
  {
    slug: 'persiapan-psikotes-kerja',
    judul: 'Persiapan Psikotes Kerja: Jenis Tes yang Sering Muncul dan Cara Menghadapinya',
    judulSeo: 'Persiapan Psikotes Kerja: Jenis Tes yang Sering Muncul (CPNS, BUMN, Swasta)',
    deskripsi: 'Panduan persiapan psikotes untuk rekrutmen kerja, BUMN, dan CPNS: jenis tes kepribadian, kemampuan, ketelitian, dan tes menggambar yang sering muncul, plus tips sebelum dan saat tes.',
    ringkas: 'Jenis tes yang umum di rekrutmen swasta, BUMN, dan CPNS, beserta persiapan yang benar-benar membantu.',
    tanggal: '2026-10-06',
    menit: 7,
    tes: { route: '/', label: 'Lihat semua latihan tes', hash: 'tes' },
    isi: [
      { p: 'Psikotes adalah salah satu tahap seleksi yang paling membuat cemas, terutama karena banyak orang tidak tahu tes apa yang akan muncul. Kabar baiknya, jenis tes yang dipakai dalam rekrutmen relatif bisa ditebak. Dengan mengenal formatnya lebih dulu, Anda bisa datang lebih tenang.' },
      { p: 'Catatan: susunan tes berbeda di setiap perusahaan, instansi, dan tahun seleksi. Selalu cek pengumuman resmi rekrutmen yang Anda ikuti.' },
      { h: '1. Tes kepribadian' },
      { p: 'Tes kepribadian menggambarkan gaya kerja, kebutuhan, dan cara Anda berinteraksi. Tidak ada jawaban benar atau salah. Yang dinilai adalah kecocokan dengan posisi dan konsistensi jawaban. Beberapa yang sering dipakai:' },
      { ul: [
        'PAPI Kostick: 90 pasangan pernyataan tentang perilaku kerja, menghasilkan profil 20 aspek.',
        'DISC: memilih kata sifat yang paling dan paling tidak menggambarkan diri, untuk membaca gaya perilaku kerja.',
        'Tes kepribadian lain seperti EPPS atau inventori berbasis model Big Five, tergantung kebijakan penyelenggara.',
      ] },
      { p: 'Persiapan terbaik untuk tes kepribadian adalah memahami diri sendiri, bukan menghafal jawaban "ideal".' },
      { h: '2. Tes kemampuan kognitif' },
      { p: 'Bagian ini menguji kemampuan berpikir dan biasanya punya jawaban benar. Umumnya terdiri dari kemampuan verbal (sinonim, antonim, analogi), numerik (deret angka, hitungan cepat, soal cerita), logika (silogisme, penalaran), dan spasial atau figural (pola gambar). Untuk bagian ini, latihan soal benar-benar membantu karena kecepatan sangat berpengaruh.' },
      { h: '3. Tes ketelitian dan ketahanan kerja' },
      { p: 'Tes seperti Kraepelin atau Pauli meminta Anda menjumlahkan angka-angka secara berurutan dalam waktu terbatas, kolom demi kolom. Yang dilihat bukan hanya jumlah jawaban benar, tetapi juga kestabilan tempo, ketelitian, dan daya tahan dari awal hingga akhir. Kuncinya: jaga ritme stabil, jangan ngebut di awal lalu kelelahan di akhir.' },
      { h: '4. Tes menggambar (proyektif)' },
      { p: 'Beberapa seleksi memakai tes menggambar, misalnya menggambar orang, pohon, atau melanjutkan pola pada kotak-kotak. Gambar dinilai oleh psikolog dari berbagai sisi, bukan dari bagus tidaknya. Gambarlah dengan wajar dan lengkap, tidak perlu artistik, dan selesaikan dalam waktu yang diberikan.' },
      { h: 'Bagaimana dengan CPNS dan BUMN?' },
      { p: 'Pada seleksi CPNS, tahap Seleksi Kompetensi Dasar (SKD) berbasis komputer berisi Tes Wawasan Kebangsaan, Tes Intelegensia Umum, dan Tes Karakteristik Pribadi. Sebagian instansi menambahkan psikotes atau tes kepribadian pada tahap seleksi berikutnya, sesuai kebutuhan jabatan.' },
      { p: 'Rekrutmen BUMN umumnya memiliki tahap tes kemampuan dasar, tes yang berkaitan dengan nilai-nilai perusahaan, dan tes kepribadian, lalu dilanjutkan wawancara. Rinciannya dapat berubah dari tahun ke tahun, jadi pantau situs resmi penyelenggara.' },
      { h: 'Tips sebelum hari tes' },
      { ul: [
        'Tidur cukup. Tes ketelitian dan kemampuan sangat dipengaruhi kondisi fisik.',
        'Kenali format tes kepribadian lebih dulu agar tidak kaget dengan soal yang berulang dan bentuk pilihan paksa.',
        'Latih soal hitungan dan logika dengan batas waktu.',
        'Siapkan perlengkapan sesuai instruksi (alat tulis, kartu identitas) dan datang lebih awal.',
      ] },
      { h: 'Tips saat mengerjakan' },
      { ul: [
        'Baca instruksi sampai selesai. Banyak kesalahan terjadi karena salah memahami cara menjawab.',
        'Pada tes kemampuan, lewati soal yang terlalu sulit dan kembali jika masih ada waktu.',
        'Pada tes kepribadian, jawab jujur dan konsisten. Jangan menebak "jawaban yang diinginkan perusahaan".',
        'Tetap tenang jika tidak semua soal selesai. Banyak tes memang dirancang agar sulit diselesaikan seluruhnya.',
      ] },
      { p: 'Latihan tes kepribadian seperti PAPI Kostick, DISC, MSDT, Big Five, dan Resiliensi Kerja bisa Anda kerjakan gratis di AssesIN untuk mengenal pola diri sebelum menghadapi seleksi.' },
      { cta: true },
    ],
  },
  {
    slug: 'tes-mbti-16-tipe-kepribadian',
    judul: 'Tes MBTI: Arti 4 Dimensi, 16 Tipe Kepribadian, dan Cara Memakai Hasilnya',
    judulSeo: 'Tes MBTI: Arti 4 Dimensi & 16 Tipe Kepribadian',
    deskripsi: 'Penjelasan tes MBTI: empat dimensi (E/I, S/N, T/F, J/P), cara membaca kode empat huruf seperti INTJ atau ESFP, kegunaan dan keterbatasannya, serta cara memakai hasilnya untuk karier.',
    ringkas: 'Empat dimensi MBTI, cara membaca kode empat huruf, dan apa yang bisa (dan tidak bisa) disimpulkan dari hasilnya.',
    tanggal: '2026-10-07',
    menit: 6,
    tes: { route: '/tes', label: 'Coba tes MBTI gratis' },
    isi: [
      { p: 'INTJ, ENFP, ISTJ: kode empat huruf ini sering muncul di bio media sosial, obrolan kantor, sampai sesi pengembangan karyawan. Semuanya berasal dari kerangka MBTI, salah satu model tipe kepribadian yang paling populer di dunia.' },
      { h: 'Apa itu MBTI?' },
      { p: 'MBTI (Myers-Briggs Type Indicator) dikembangkan oleh Katharine Cook Briggs dan putrinya, Isabel Briggs Myers, berdasarkan teori tipe psikologis Carl Jung. Tujuannya membantu orang memahami preferensi alaminya: dari mana energi didapat, bagaimana informasi diserap, bagaimana keputusan diambil, dan bagaimana menata hidup sehari-hari.' },
      { p: 'Kata kuncinya adalah preferensi. MBTI tidak mengukur kemampuan, kecerdasan, atau kesehatan mental. Orang bertipe introvert tetap bisa berbicara di depan umum; ia hanya cenderung lebih cepat lelah setelahnya.' },
      { h: 'Empat dimensi MBTI' },
      { ul: [
        'E (Extraversion) atau I (Introversion): sumber energi. E mendapat energi dari interaksi dan aktivitas; I mendapat energi dari waktu sendiri dan refleksi.',
        'S (Sensing) atau N (Intuition): cara menyerap informasi. S fokus pada fakta konkret dan pengalaman nyata; N fokus pada pola, kemungkinan, dan gambaran besar.',
        'T (Thinking) atau F (Feeling): cara mengambil keputusan. T mengutamakan logika dan konsistensi; F mengutamakan nilai pribadi dan dampaknya pada orang lain.',
        'J (Judging) atau P (Perceiving): cara menata hidup. J menyukai rencana dan keputusan yang tuntas; P menyukai fleksibilitas dan membiarkan pilihan tetap terbuka.',
      ] },
      { p: 'Satu huruf dari setiap dimensi digabung menjadi kode empat huruf, sehingga ada 16 kemungkinan tipe. Contohnya ISTJ: introvert, berpegang pada fakta, logis, dan terencana. Kebalikannya, ENFP: ekstrovert, imajinatif, berpegang pada nilai, dan spontan.' },
      { h: 'Bentuk soal tes MBTI' },
      { p: 'Soal tes bergaya MBTI umumnya berupa pernyataan atau pilihan situasi, lalu Anda memilih yang paling sesuai dengan diri Anda. Contoh ilustrasi (bukan soal asli): "Setelah seminggu penuh bekerja, Anda lebih ingin (a) bertemu teman-teman, atau (b) menghabiskan akhir pekan dengan tenang di rumah." Jawaban-jawaban ini dijumlahkan per dimensi untuk menentukan kecenderungan Anda.' },
      { h: 'Apa kegunaan hasil MBTI?' },
      { ul: [
        'Mengenal diri: memahami kenapa situasi tertentu terasa melelahkan atau justru menyenangkan.',
        'Komunikasi tim: menyadari bahwa rekan kerja bisa memproses informasi dan mengambil keputusan dengan cara yang berbeda.',
        'Eksplorasi karier: memberi gambaran lingkungan kerja yang lebih cocok, misalnya pekerjaan yang terstruktur atau yang dinamis.',
      ] },
      { h: 'Keterbatasan yang perlu Anda ketahui' },
      { p: 'MBTI mengelompokkan orang ke dalam salah satu dari dua kutub, padahal banyak orang berada di tengah-tengah. Karena itu hasil tes bisa berubah jika Anda mengerjakannya ulang, terutama pada dimensi yang skornya tipis. Para peneliti psikologi juga lebih sering memakai model Big Five untuk penelitian kepribadian.' },
      { p: 'Artinya, pakailah MBTI sebagai bahan refleksi dan diskusi, bukan sebagai label permanen atau dasar tunggal untuk menolak sebuah pilihan karier. Banyak perusahaan juga tidak memakai MBTI sebagai alat seleksi, melainkan untuk pengembangan tim.' },
      { h: 'Tips mengerjakan tes MBTI' },
      { ul: [
        'Jawab berdasarkan kebiasaan alami Anda, bukan tuntutan pekerjaan atau sosok yang Anda inginkan.',
        'Kerjakan saat tenang dan tidak terburu-buru.',
        'Jika ada dimensi yang skornya hampir seimbang, baca deskripsi kedua kutubnya dan nilai sendiri mana yang lebih menggambarkan Anda.',
      ] },
      { p: 'Di AssesIN Anda bisa mengerjakan tes MBTI 60 soal secara gratis dan langsung melihat tipe Anda beserta ringkasan karakternya.' },
      { cta: true },
    ],
  },
  {
    slug: 'tes-msdt-gaya-kepemimpinan',
    judul: 'Tes MSDT: Delapan Gaya Kepemimpinan dan Cara Membaca Hasilnya',
    judulSeo: 'Tes MSDT: 8 Gaya Kepemimpinan & Cara Membaca Hasilnya',
    deskripsi: 'Panduan tes MSDT (Management Style Diagnostic Test) untuk seleksi supervisor dan manajer: teori 3-D Reddin, orientasi tugas dan hubungan, delapan gaya kepemimpinan, dan tips mengerjakannya.',
    ringkas: 'Teori di balik MSDT, orientasi tugas dan hubungan, delapan gaya manajemen, dan cara menghadapinya saat seleksi.',
    tanggal: '2026-10-07',
    menit: 6,
    tes: { route: '/tes-msdt', label: 'Coba latihan tes MSDT' },
    isi: [
      { p: 'Jika Anda melamar posisi supervisor, kepala seksi, atau manajer, kemungkinan besar Anda akan menemui tes MSDT. Tes ini sering dipakai dalam seleksi dan promosi jabatan untuk membaca gaya kepemimpinan seseorang.' },
      { h: 'Apa itu MSDT?' },
      { p: 'MSDT (Management Style Diagnostic Test) berakar dari teori kepemimpinan 3-D yang dikembangkan oleh William J. Reddin. Menurut teori ini, tidak ada satu gaya kepemimpinan yang selalu paling baik. Sebuah gaya bisa efektif dalam satu situasi tetapi kurang efektif dalam situasi lain.' },
      { h: 'Tiga dimensi yang dilihat' },
      { ul: [
        'Task Orientation (TO): seberapa besar perhatian Anda pada tugas, target, perencanaan, dan pengawasan hasil kerja.',
        'Relationship Orientation (RO): seberapa besar perhatian Anda pada hubungan, kepercayaan, dan kebutuhan anggota tim.',
        'Effectiveness (E): seberapa tepat gaya yang Anda pakai dengan tuntutan situasi.',
      ] },
      { p: 'Kombinasi TO dan RO menghasilkan empat gaya dasar. Masing-masing punya versi yang lebih efektif dan versi yang kurang efektif, sehingga totalnya delapan gaya.' },
      { h: 'Delapan gaya kepemimpinan MSDT' },
      { ul: [
        'TO tinggi, RO tinggi: Executive (efektif), yaitu pemimpin yang menetapkan standar tinggi sekaligus melibatkan tim; atau Compromiser (kurang efektif), yang berusaha menyenangkan semua pihak sehingga keputusannya sering setengah-setengah.',
        'TO tinggi, RO rendah: Benevolent Autocrat (efektif), yang tegas mengarahkan tanpa menimbulkan penolakan; atau Autocrat (kurang efektif), yang memaksakan kehendak dan kurang peduli pada perasaan tim.',
        'TO rendah, RO tinggi: Developer (efektif), yang menumbuhkan potensi dan kepercayaan tim; atau Missionary (kurang efektif), yang terlalu mementingkan suasana harmonis hingga target terabaikan.',
        'TO rendah, RO rendah: Bureaucrat (efektif), yang menjaga aturan dan prosedur dengan konsisten; atau Deserter (kurang efektif), yang menarik diri dan menghindari tanggung jawab.',
      ] },
      { h: 'Bentuk soal tes MSDT' },
      { p: 'Versi yang umum dipakai berisi 64 nomor. Setiap nomor berisi dua pernyataan tentang sikap atau tindakan seorang pemimpin, dan Anda memilih satu yang lebih menggambarkan diri Anda. Contoh ilustrasi (bukan soal asli): "A. Saya memastikan setiap anggota tim tahu target mingguannya" atau "B. Saya meluangkan waktu menanyakan kesulitan yang dihadapi anggota tim."' },
      { h: 'Bagaimana hasilnya dibaca saat seleksi?' },
      { p: 'Panitia seleksi biasanya mencocokkan gaya Anda dengan kebutuhan jabatan. Posisi yang menuntut perubahan cepat dan target ketat mungkin membutuhkan orientasi tugas yang kuat, sedangkan posisi yang memimpin tim baru atau tim ahli mungkin membutuhkan orientasi hubungan yang kuat. Gaya yang tergolong efektif umumnya dinilai lebih positif, tetapi asesor juga melihat kecocokan dengan konteks dan hasil asesmen lain seperti wawancara atau simulasi.' },
      { h: 'Tips mengerjakan tes MSDT' },
      { ul: [
        'Bayangkan diri Anda dalam peran memimpin, meskipun saat ini belum menjabat. Pengalaman memimpin proyek, organisasi, atau kepanitiaan bisa menjadi acuan.',
        'Jawab sesuai tindakan yang benar-benar Anda lakukan, bukan yang terdengar paling ideal. Banyak pasangan pernyataan dibuat sama-sama baik.',
        'Jaga konsistensi. Pola jawaban yang berubah-ubah membuat profil sulit dibaca.',
        'Setelah tahu gaya Anda, siapkan contoh nyata untuk wawancara: kapan gaya itu berhasil, dan kapan Anda perlu menyesuaikan diri.',
      ] },
      { p: 'Di AssesIN Anda bisa mengerjakan latihan MSDT 64 soal secara gratis dan melihat gaya kepemimpinan dominan Anda.' },
      { cta: true },
    ],
  },
  {
    slug: 'tes-dass-21-depresi-kecemasan-stres',
    judul: 'Tes DASS-21: Cara Kerja, Arti Skor Depresi, Kecemasan, dan Stres',
    judulSeo: 'Tes DASS-21: Arti Skor Depresi, Kecemasan & Stres',
    deskripsi: 'Penjelasan tes DASS-21: apa yang diukur, cara skor dihitung, arti kategori normal hingga sangat berat untuk depresi, kecemasan, dan stres, serta kapan sebaiknya mencari bantuan profesional.',
    ringkas: 'Apa yang diukur DASS-21, cara membaca kategorinya, dan kapan hasil skrining perlu ditindaklanjuti.',
    tanggal: '2026-10-07',
    menit: 5,
    tes: { route: '/tes-dass', label: 'Coba skrining DASS-21' },
    isi: [
      { p: 'Kadang kita merasa lelah, gelisah, atau mudah tersinggung tanpa tahu seberapa serius kondisinya. DASS-21 adalah salah satu kuesioner yang paling banyak dipakai untuk membantu memetakan hal itu secara singkat.' },
      { h: 'Apa itu DASS-21?' },
      { p: 'DASS (Depression Anxiety Stress Scales) dikembangkan oleh Peter dan Sydney Lovibond dari University of New South Wales, Australia. DASS-21 adalah versi pendek berisi 21 pernyataan, tujuh untuk masing-masing skala: depresi, kecemasan, dan stres. Kuesioner ini dipakai luas dalam penelitian dan layanan kesehatan, termasuk di Indonesia.' },
      { h: 'Apa saja yang diukur?' },
      { ul: [
        'Depresi: perasaan sedih atau hampa, hilangnya minat dan semangat, serta pandangan negatif terhadap diri dan masa depan.',
        'Kecemasan: rasa takut atau panik, serta gejala fisik seperti jantung berdebar, mulut kering, atau gemetar.',
        'Stres: sulit rileks, tegang, mudah gelisah, dan mudah tersinggung atau bereaksi berlebihan.',
      ] },
      { h: 'Bagaimana cara mengerjakannya?' },
      { p: 'Anda membaca setiap pernyataan lalu menilai seberapa sering hal itu Anda alami selama satu minggu terakhir, dari 0 (tidak pernah) sampai 3 (sangat sering atau hampir selalu). Karena acuannya satu minggu terakhir, hasil DASS-21 menggambarkan kondisi saat ini, bukan sifat yang menetap.' },
      { h: 'Cara membaca skor' },
      { p: 'Skor tiap skala dijumlahkan lalu dikalikan dua agar setara dengan versi lengkap DASS-42, sehingga rentangnya 0 sampai 42. Skor tersebut kemudian dikelompokkan ke dalam lima kategori: normal, ringan, sedang, berat, dan sangat berat. Batas kategorinya berbeda untuk setiap skala:' },
      { ul: [
        'Depresi: normal 0–9, ringan 10–13, sedang 14–20, berat 21–27, sangat berat 28 ke atas.',
        'Kecemasan: normal 0–7, ringan 8–9, sedang 10–14, berat 15–19, sangat berat 20 ke atas.',
        'Stres: normal 0–14, ringan 15–18, sedang 19–25, berat 26–33, sangat berat 34 ke atas.',
      ] },
      { h: 'Skrining, bukan diagnosis' },
      { p: 'DASS-21 adalah alat skrining. Hasilnya menunjukkan seberapa besar keluhan yang Anda rasakan, tetapi tidak bisa menggantikan pemeriksaan oleh psikolog atau psikiater. Skor tinggi bisa dipengaruhi banyak hal, misalnya kurang tidur, masalah kesehatan fisik, atau peristiwa berat yang baru terjadi. Sebaliknya, skor normal juga tidak berarti Anda tidak boleh mencari bantuan jika merasa membutuhkannya.' },
      { h: 'Kapan sebaiknya mencari bantuan profesional?' },
      { ul: [
        'Jika skor Anda berada pada kategori sedang, berat, atau sangat berat, terutama bila berlangsung lebih dari dua minggu.',
        'Jika keluhan mulai mengganggu pekerjaan, kuliah, tidur, atau hubungan dengan orang terdekat.',
        'Jika muncul pikiran untuk menyakiti diri sendiri atau mengakhiri hidup. Segera hubungi orang yang Anda percaya, datangi IGD terdekat, atau hubungi layanan kesehatan jiwa Kementerian Kesehatan di 119 ekstensi 8.',
      ] },
      { p: 'Puskesmas, rumah sakit, layanan konseling kampus, dan biro psikologi bisa menjadi tempat awal untuk berkonsultasi.' },
      { h: 'Tips agar hasilnya bermakna' },
      { ul: [
        'Kerjakan di tempat yang tenang dan jawab jujur. Tidak ada yang menilai jawaban Anda.',
        'Ingat acuannya: seminggu terakhir, bukan sepanjang hidup.',
        'Ulangi beberapa minggu kemudian untuk melihat apakah kondisi Anda membaik atau perlu perhatian lebih.',
      ] },
      { p: 'Di AssesIN Anda bisa mengerjakan skrining DASS-21 dalam sekitar lima menit dan langsung melihat kategori skor depresi, kecemasan, dan stres Anda.' },
      { cta: true },
    ],
  },
]

export const ARTIKEL_BY_SLUG = Object.fromEntries(ARTIKEL.map(a => [a.slug, a]))
